service: gestion-vuelos-usuarios

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    AEROLINEAS_TABLE: Aerolíneas
    VUELOS_TABLE: Vuelos
    USUARIOS_TABLE: Usuarios
    TOKENS_TABLE: TokensAcceso

functions:
  # Funciones para Aerolíneas
  createAerolinea:
    handler: create_aerolineas.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: post

  searchAerolinea:
    handler: search_aerolineas.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: get

  updateAerolinea:
    handler: update_aerolineas.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: put

  deleteAerolinea:
    handler: delete_aerolineas.lambda_handler
    events:
      - http:
          path: /aerolineas
          method: delete

  # Funciones para Vuelos
  createVuelo:
    handler: create_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: post

  searchVuelo:
    handler: search_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: get

  updateVuelo:
    handler: update_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: put

  deleteVuelo:
    handler: delete_vuelo.lambda_handler
    events:
      - http:
          path: /vuelos
          method: delete

  # Funciones para Usuarios
  createUsuario:
    handler: LambdaCrearUsuario.lambda_handler
    events:
      - http:
          path: /usuarios
          method: post

  buscarUsuario:
    handler: LambdaBuscarUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/{user_id}
          method: get

  modificarUsuario:
    handler: LambdaModificarUsuario.lambdahandler
    events:
      - http:
          path: /usuarios
          method: put

  loginUsuario:
    handler: LambdaLogin.lambda_handler
    events:
      - http:
          path: /usuarios/login
          method: post

  validarToken:
    handler: LambdaValidarTokenAcceso.lambda_handler
    events:
      - http:
          path: /usuarios/token/validar
          method: post

resources:
  Resources:
    # Tabla Aerolíneas
    AerolineasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.AEROLINEAS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_aerolinea
            AttributeType: S
        KeySchema:
          - AttributeName: id_aerolinea
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # Tabla Vuelos
    VuelosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.VUELOS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_vuelo
            AttributeType: S
        KeySchema:
          - AttributeName: id_vuelo
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # Tabla Usuarios
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USUARIOS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # Tabla Tokens de Acceso
    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
